spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://web-study.ctumsyopmesy.ap-northeast-2.rds.amazonaws.com:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  #    url: jdbc:log4jdbc:mariadb://web-study.ctumsyopmesy.ap-northeast-2.rds.amazonaws.com:3306/project_winiaaid?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r